package com.p3solutions.archon_report_utility;

import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.VerticalAlignment;
import com.p3solutions.archon_report_utility.beans.FooterBean;
import com.p3solutions.archon_report_utility.beans.HeaderBean;
import com.p3solutions.archon_report_utility.beans.TableBean;
import com.p3solutions.archon_report_utility.core.Report;
import com.p3solutions.archon_report_utility.core.ReportBuilder;
import com.p3solutions.archon_report_utility.enums.DividerType;
import com.p3solutions.archon_report_utility.enums.FontType;
import com.p3solutions.archon_report_utility.enums.TableTypeEnum;
import com.p3solutions.archon_report_utility.interfaces.ReportComponent;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import static com.p3solutions.archon_report_utility.builder.ChartCreationConfigUtil.buildChartCreationConfig;
import static com.p3solutions.archon_report_utility.builder.DividerBeanBuilder.buildDividerInputBean;
import static com.p3solutions.archon_report_utility.builder.SummaryBeanBuilder.buildSummaryBean;
import static com.p3solutions.archon_report_utility.constants.ColorConstants.GREY_COLOR;
import static com.p3solutions.archon_report_utility.constants.ColorConstants.GREY_LINE_COLOR;

public class ReportGenerator {
    public static void main(String[] args) {
        try {

            String outputPath = "C:\\Users\\P3INW82\\IdeaProjects\\Archon_Common_Report\\src\\report";

            Map<String, String> parameters = new LinkedHashMap<>();
            parameters.put("Generated By", "Sysadmin");
            parameters.put("Job Name", "Test Job");
            parameters.put("Report Generated Time", new Date().toString());

            Map<String, String> jobSummaryParameters = new LinkedHashMap<>();
            jobSummaryParameters.put("Scheduled By", "Sysadmin");
            jobSummaryParameters.put("Scheduled Time", new Date().toString());
            jobSummaryParameters.put("Start Time", new Date().toString());
            jobSummaryParameters.put("End Time", new Date().toString());
            jobSummaryParameters.put("Total Time", new Date().toString());


            Report report = new ReportBuilder(outputPath).build();
            ReportComponent dividerComponent = ReportBuilder.addComponent(buildDividerInputBean(805L, 0.5f, GREY_COLOR, 1, DividerType.PAGE_TO_PAGE));
            ReportComponent tableComponent = ReportBuilder.addComponent(getTableBean(parameters));
            ReportComponent dividerComponent1 = ReportBuilder.addComponent(buildDividerInputBean(780L, 1, GREY_COLOR, 1, DividerType.CONTENT));
            ReportComponent jobSummaryComponent = ReportBuilder.addComponent(buildSummaryBean("Job Summary", GREY_LINE_COLOR, 10, FontType.HELVETICA_BOLD.getFontName(),
                    TextAlignment.LEFT,
                    VerticalAlignment.TOP));
            ReportComponent dividerComponent2 = ReportBuilder.addComponent(buildDividerInputBean(760L, 1L, GREY_COLOR, 1, DividerType.CONTENT));
            ReportComponent jobTableComponent = ReportBuilder.addComponent(getTableBean(jobSummaryParameters));
            ReportComponent dividerComponent3 = ReportBuilder.addComponent(buildDividerInputBean(680L, 1L, GREY_COLOR, 1, DividerType.CONTENT));
            ReportComponent objectiveHeaderComponent = ReportBuilder.addComponent(buildSummaryBean("Objective", GREY_LINE_COLOR, 10, FontType.HELVETICA_BOLD.getFontName(),
                    TextAlignment.LEFT,
                    VerticalAlignment.TOP));
            ReportComponent fileObjectiveValue = ReportBuilder.addComponent(buildSummaryBean(
                    """
                            The License Volume Statistics Report provides detailed insights into the utilization of software licenses within an organization. It includes metrics on the total number of licenses available, the number of licenses currently in use, and any remaining or unused licenses. This report helps organizations manage compliance, optimize license allocation, and plan for future licensing needs, ensuring cost-effective use of software resources and adherence to licensing agreements.
                            """,
                    "0D0D0D", 8, FontType.HELVETICA.getFontName(),
                    TextAlignment.LEFT,
                    VerticalAlignment.TOP));
            ReportComponent licenseVolumeMetrics = ReportBuilder.addComponent(buildSummaryBean("License Volume Metrics", GREY_LINE_COLOR, 10, FontType.HELVETICA_BOLD.getFontName(),
                    TextAlignment.LEFT,
                    VerticalAlignment.TOP));
            ReportComponent dividerComponent4 = ReportBuilder.addComponent(buildDividerInputBean(605L, 1L, GREY_COLOR, 1, DividerType.CONTENT));
            ReportComponent footerDivider = ReportBuilder.addComponent(buildDividerInputBean(30L, 1L, GREY_COLOR, 1, DividerType.PAGE_TO_PAGE));
            ReportComponent headerComponent = ReportBuilder.addComponent(new HeaderBean());
            ReportComponent footerComponent = ReportBuilder.addComponent(new FooterBean());
            ReportComponent chartComponent = ReportBuilder.addComponent(buildChartCreationConfig());

            report.addComponent(tableComponent);
            report.addComponent(dividerComponent1);
            report.addComponent(jobSummaryComponent);
            report.addComponent(dividerComponent2);
            report.addComponent(jobTableComponent);
            report.addComponent(dividerComponent3);
            report.addComponent(objectiveHeaderComponent);
            report.addComponent(fileObjectiveValue);
            report.addComponent(licenseVolumeMetrics);
            report.addComponent(dividerComponent4);
            report.addComponent(chartComponent);
            report.addComponent(headerComponent);
            report.addComponent(dividerComponent);
            report.addComponent(footerComponent);
            report.addComponent(footerDivider);
            report.render();
            report.close();

        } catch (FileNotFoundException e) {
            throw new IllegalArgumentException(e.getMessage());
        } catch (IOException e) {
            throw new IllegalArgumentException(e);
        }
    }

    private static TableBean getTableBean(Map<String, String> parameters) {
        return TableBean.builder()
                .numberOfColumns(3)
                .pointColumnWidth(new float[]{450L, 450L, 450L})
                .width(100)
                .border(Border.NO_BORDER)
                .keepTogether(true)
                .parameters(parameters)
                .type(TableTypeEnum.POINT_COLUMN_WIDTH)
                .build();
    }

}
