package com.p3solutions.archon_report_utility;

import static com.p3solutions.archon_report_utility.builder.ChartCreationConfigUtil.buildChartCreationConfig;
import static com.p3solutions.archon_report_utility.builder.DividerBeanBuilder.buildDividerInputBean;
import static com.p3solutions.archon_report_utility.builder.SummaryBeanBuilder.buildSummaryBean;
import static com.p3solutions.archon_report_utility.builder.TableBuilder.getTableBean;
import static com.p3solutions.archon_report_utility.constants.ColorConstants.*;

import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.VerticalAlignment;
import com.p3solutions.archon_report_utility.beans.FooterBean;
import com.p3solutions.archon_report_utility.beans.HeaderBean;
import com.p3solutions.archon_report_utility.core.Report;
import com.p3solutions.archon_report_utility.core.ReportBuilder;
import com.p3solutions.archon_report_utility.enums.DividerType;
import com.p3solutions.archon_report_utility.enums.FontType;
import com.p3solutions.archon_report_utility.enums.TableType;
import com.p3solutions.archon_report_utility.interfaces.ReportComponent;
import runner.enums.ReportNameConstants;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

public class ReportGenerator {
  public static void main(String[] args) {
    try {

      String outputPath = "/home/p3/Downloads/archon-report-utility/output";

      Map<String, String> parameters = new LinkedHashMap<>();
      parameters.put("Generated By", "Sysadmin");
      parameters.put("Job Name", "Test Job");
      parameters.put("Report Generated Time", new Date().toString());

      Map<String, String> jobSummaryParameters = new LinkedHashMap<>();
      jobSummaryParameters.put("Scheduled By", "Sysadmin");
      jobSummaryParameters.put("Scheduled Time", new Date().toString());
      jobSummaryParameters.put("Start Time", new Date().toString());
      jobSummaryParameters.put("End Time", new Date().toString());
      jobSummaryParameters.put("Total Time", new Date().toString());

      Report report = new ReportBuilder(outputPath, "Report.pdf").build();
      ReportComponent tableComponent =
              ReportBuilder.addComponent(getTableBean(parameters, TableType.HEADER));
      ReportComponent dividerComponent =
              ReportBuilder.addComponent(
                      buildDividerInputBean(760L, 1L, HEADER_TABLE_DIVIDER_GREY_COLOR, 1, DividerType.PAGE_TO_PAGE));
      ReportComponent jobSummaryComponent =
              ReportBuilder.addComponent(
                      buildSummaryBean(
                              "Job Summary",
                              HEADER_FONT_COLOR,
                              13,
                              FontType.HELVETICA_BOLD.getFontName(),
                              TextAlignment.LEFT,
                              VerticalAlignment.TOP));
      ReportComponent summaryDividerComponent =
              ReportBuilder.addComponent(
                      buildDividerInputBean(740L, 1L, DIVIDER_GREY_COLOR, 1, DividerType.CONTENT));

      ReportComponent jobTableComponent =
              ReportBuilder.addComponent(getTableBean(jobSummaryParameters, TableType.SUMMARY));
      ReportComponent objectiveHeaderComponent =
              ReportBuilder.addComponent(
                      buildSummaryBean(
                              "Objective",
                              HEADER_FONT_COLOR,
                              13,
                              FontType.HELVETICA_BOLD.getFontName(),
                              TextAlignment.LEFT,
                              VerticalAlignment.TOP));
      ReportComponent dividerAfterObjective =
              ReportBuilder.addComponent(
                      buildDividerInputBean(640L, 1L, DIVIDER_GREY_COLOR, 1, DividerType.CONTENT));
      String reportDescription =
              "The License Volume Statistics Report provides detailed insights into the utilization of software licenses within an organization. "
                      + "It includes metrics on the total number of licenses available, the number of licenses currently in use, and any remaining or unused licenses. "
                      + "This report helps organizations manage compliance, optimize license allocation, and plan for future licensing needs, ensuring cost-effective use of software resources and adherence to licensing agreements.";
      ReportComponent fileObjectiveValue =
              ReportBuilder.addComponent(
                      buildSummaryBean(
                              reportDescription,
                              OBJECTIVE_FONT_COLOR,
                              10,
                              FontType.HELVETICA.getFontName(),
                              TextAlignment.LEFT,
                              VerticalAlignment.TOP));
      ReportComponent licenseVolumeMetrics =
              ReportBuilder.addComponent(
                      buildSummaryBean(
                              "License Volume Metrics",
                              HEADER_FONT_COLOR,
                              13,
                              FontType.HELVETICA_BOLD.getFontName(),
                              TextAlignment.LEFT,
                              VerticalAlignment.TOP));
      ReportComponent licenseVolumeMetricDivider =
              ReportBuilder.addComponent(
                      buildDividerInputBean(538L, 1L, DIVIDER_GREY_COLOR, 1, DividerType.CONTENT));
      ReportComponent headerComponent = ReportBuilder.addComponent(new HeaderBean());
      ReportComponent footerComponent = ReportBuilder.addComponent(new FooterBean());
      ReportComponent chartComponent = ReportBuilder.addComponent(buildChartCreationConfig(ReportNameConstants.getReportNameConstants("License Volume Statistics Report")));


      report.addComponent(headerComponent);
      report.addComponent(tableComponent);
      report.addComponent(dividerComponent);
      report.addComponent(jobSummaryComponent);
      report.addComponent(summaryDividerComponent);
      report.addComponent(jobTableComponent);
      report.addComponent(objectiveHeaderComponent);
      report.addComponent(dividerAfterObjective);
      report.addComponent(fileObjectiveValue);
      report.addComponent(licenseVolumeMetrics);
      report.addComponent(licenseVolumeMetricDivider);
      report.addComponent(chartComponent);
      report.addComponent(footerComponent);
      report.render();
      report.close();

    } catch (FileNotFoundException e) {
      throw new IllegalArgumentException(e.getMessage());
    } catch (IOException e) {
      throw new IllegalArgumentException(e);
    }
  }
}
